export const nigerianBanks = [
    '5TT MFB',
    '78 Finance Company Ltd',
    '9jaPay Microfinance Bank',
    '9mobile 9Payment Service Bank',
    'Abbey Mortgage Bank',
    'Above Only MFB',
    'Abulesoro MFB',
    'Access Bank',
    'Access Bank (Diamond)',
    'Accion Microfinance Bank',
    'Adamawa Mortgage Bank Limited',
    'Advancly MFB',
    'Aella MFB',
    'AG Mortgage Bank',
    'Ahmadu Bello University Microfinance Bank',
    'Airtel Smartcash PSB',
    'AKU Microfinance Bank',
    'Akuchukwu Microfinance Bank Limited',
    'Al-Barakah Microfinance Bank',
    'ALAT by WEMA',
    'Alert MFB',
    'ALLWORKERS MFB',
    'Alpha Morgan Bank',
    'Alternative bank',
    'Amju Unique MFB',
    'Aramoko MFB',
    'ASO Savings and Loans',
    'ASSET MATRIX MFB',
    'Assets Microfinance Bank',
    'Astrapolaris MFB LTD',
    'ATBU MFB',
    'AVUENEGBE MICROFINANCE BANK',
    'AWACASH MICROFINANCE BANK',
    'AZTEC MICROFINANCE BANK LIMITED',
    'Bainescredit MFB',
    'Banc Corp Microfinance Bank',
    'BANK OF AGRICULTURE',
    'Bank78 Microfinance Bank',
    'BANKIT MFB',
    'BANKIT MICROFINANCE BANK LTD',
    'BANKLY MFB',
    'Baobab Microfinance Bank',
    'BC Kash Microfinance Bank',
    'BellBank Microfinance Bank',
    'Benysta Microfinance Bank Limited',
    'Berachah Microfinance Bank Ltd.',
    'Beststar Microfinance Bank',
    'BLOC MFB',
    'BOLD MFB',
    'Boost Microfinance Bank',
    'Bosak Microfinance Bank',
    'Bowen Microfinance Bank',
    'Branch International Finance Company Limited',
    'Brent Mortgage bank',
    'BuyPower MFB',
    'BWAY MFB',
    'Carbon',
    'Cashbridge Microfinance Bank Limited',
    'CASHCONNECT MFB',
    'Cedrus MFB',
    'CEMCS Microfinance Bank',
    'Centrum Finance',
    'CHAMS MOBILE MFB',
    'Chanelle Microfinance Bank Limited',
    'Chikum Microfinance bank',
    'Citibank Nigeria',
    'CITYCODE MORTAGE BANK',
    'Civic Microfinance Bank Limited',
    'Consumer Microfinance Bank',
    'Cool Microfinance Bank Limited',
    'Cooperative Mortgage Bank',
    'Corestep MFB',
    'Coronation Merchant Bank',
    'County Finance Limited',
    'Credit Direct Limited',
    'Crescent MFB',
    'Crust Microfinance Bank',
    'CRUTECH MICROFINANCE BANK LTD',
    'Dash Microfinance Bank',
    'Davenport MICROFINANCE BANK',
    'Dillon Microfinance Bank',
    'Dot Microfinance Bank',
    'EBSU Microfinance Bank',
    'Ecobank Nigeria',
    'Ekimogun MFB',
    'Ekondo Microfinance Bank',
    'ESO-E MICROFINANCE BANK LIMITED',
    'Ethica MFB',
    'EXCEL FINANCE BANK',
    'Eyowo',
    'Fairmoney Microfinance Bank',
    'FCMB MFB',
    'Fedeth MFB',
    'Fewchore Finance Company Limited',
    'FFS Microfinance Bank',
    'Fidelity Bank',
    'Firmus MFB',
    'First Bank of Nigeria',
    'First City Monument Bank',
    'First Option MFB',
    'FIRST ROYAL MICROFINANCE BANK',
    'FIRSTMIDAS MFB',
    'FirstTrust Mortgage Bank Nigeria',
    'Flutterwave MFB',
    'Fortress MFB',
    'FSDH Merchant Bank Limited',
    'FUTMINNA MICROFINANCE BANK',
    'Garun Mallam MFB',
    'Globus Bank',
    'GLORY MFB',
    'Goldman MFB',
    'GOMBE MFB',
    'GoMoney',
    'GOOD SHEPHERD MICROFINANCE BANK',
    'Goodnews Microfinance Bank',
    'GRANTS MFB',
    'Greenwich Merchant Bank',
    'GROOMING MICROFINANCE BANK',
    'GTI MFB',
    'Guaranty Trust Bank',
    'Hackman Microfinance Bank',
    'Haggai Mortgage Bank',
    'Hasal Microfinance Bank',
    'Hayat Trust MFB',
    'HopePSB',
    'IBANK Microfinance Bank',
    'IBBU MFB',
    'Ibile Microfinance Bank',
    'Ibom Mortgage Bank',
    'Ikoyi Osun MFB',
    'Ilaro Poly Microfinance Bank',
    'Imowo MFB',
    'IMPERIAL HOMES MORTAGE BANK',
    'INEBA GOGO MFB',
    'Infinity MFB',
    'Infinity trust  Mortgage Bank',
    'ISUA MFB',
    'Jaiz Bank',
    'Jubilee Life Mortgage Bank',
    'Kadpoly MFB',
    'KANOPOLY MFB',
    'KAYI MFB',
    'Kayvee Microfinance Bank',
    'Kebbi Homes Savings and Loans Limited',
    'Keystone Bank',
    'Kolomoni MFB',
    'Kolomoni Microfinance Bank',
    'KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)',
    'Kredi Money MFB LTD',
    'Kuda Bank',
    'Lagos Building Investment Company Plc.',
    'Lemmy MFB',
    'Letshego Microfinance Bank',
    'Links MFB',
    'Living Trust Mortgage Bank',
    'LOMA MFB',
    'Lotus Bank',
    'Maal MFB',
    'MAHFUZ MFB',
    'MAINSTREET MICROFINANCE BANK',
    'Mayden Microfinance Bank',
    'Mayfair MFB',
    'Mayfresh Mortgage Bank',
    'Mega Microfinance Bank',
    'Michael Okpara UniAgric Microfinance Bank',
    'Mint MFB',
    'MINT-FINEX MFB',
    'Money Master PSB',
    'Moniepoint MFB',
    'MOVASCO MFB',
    'MTN Momo PSB',
    'MUTUAL BENEFITS MICROFINANCE BANK',
    'NDCC MICROFINANCE BANK',
    'NET MICROFINANCE BANK',
    'Nigerian Navy Microfinance Bank Limited',
    'NIRSAL MICROFINANCE',
    'Nombank MFB',
    'NOVA BANK',
    'Novus MFB',
    'NPF MICROFINANCE BANK',
    'NSUK MICROFINANACE BANK',
    'NUVION MFB',
    'Olabisi Onabanjo University Microfinance Bank',
    'OLUCHUKWU MICROFINANCE BANK LTD',
    'OPay Digital Services Limited (OPay)',
    'Optimus Bank Limited',
    'Pact Microfinance Bank',
    'Paga',
    'PalmPay',
    'Parallex Bank',
    'Parkway - ReadyCash',
    'PATHFINDER MICROFINANCE BANK LIMITED',
    'PATRICKGOLD MFB',
    'Paystack MFB',
    'Paystack-Titan',
    'Peace Microfinance Bank',
    'PECANTRUST MICROFINANCE BANK LIMITED',
    'Personal Trust MFB',
    'Petra Mircofinance Bank Plc',
    'Pettysave MFB',
    'PFI FINANCE COMPANY LIMITED',
    'Platinum Mortgage Bank',
    'Pocket App',
    'Polaris Bank',
    'Polyunwana MFB',
    'PremiumTrust Bank',
    'Prospa Capital Microfinance Bank',
    'PROSPERIS FINANCE LIMITED',
    'Providus Bank',
    'QuickFund MFB',
    'Rand Merchant Bank',
    'RANDALPHA MICROFINANCE BANK',
    'Rank MFB',
    'Refuge Mortgage Bank',
    'REHOBOTH MICROFINANCE BANK',
    'RenMoney Microfinance Bank',
    'Rephidim Microfinance Bank',
    'Retrust Mfb',
    'Rex Microfinance Bank',
    'Rigo Microfinance Bank Limited',
    'ROCKSHIELD MICROFINANCE BANK',
    'RSU MICROFINANCE BANK',
    'Rubies MFB',
    'Safe Haven MFB',
    'SAGE GREY FINANCE LIMITED',
    'Shield MFB',
    'Signature Bank Ltd',
    'Solid Allianze MFB',
    'Solid Rock MFB',
    'SOURCE MFB',
    'Sparkle Microfinance Bank',
    'SPECTRUM MFB LTD',
    'Springfield Microfinance Bank',
    'Stanbic IBTC Bank',
    'Standard Chartered Bank',
    'STANFORD MICROFINANCE BANK',
    'STATESIDE MICROFINANCE BANK',
    'STB Mortgage Bank',
    'Stellas MFB',
    'Sterling Bank',
    'Summit Bank',
    'Suntrust Bank',
    'Supreme MFB',
    'Sycamore Microfinance Bank',
    'TAJ Bank',
    'Tangerine Money',
    'Tatum Bank',
    'Tatum Bank Ltd',
    'TENN',
    'Think Finance Microfinance Bank',
    'Titan Bank',
    'TOPRATE MFB',
    'TransPay MFB',
    'TRUSTBANC J6 MICROFINANCE BANK',
    'U and C MFB',
    'U&C Microfinance Bank Ltd (U AND C MFB)',
    'UBJ Microfinance Bank Limited',
    'UCEE MFB',
    'Uhuru MFB',
    'Ultraviolet Microfinance Bank',
    'Umunnachi Microfinance Bank Ltd',
    'Unaab Microfinance Bank Limited',
    'UNIABUJA MFB',
    'Unical MFB',
    'Unilag Microfinance Bank',
    'UNIMAID MICROFINANCE BANK',
    'Union Bank of Nigeria',
    'United Bank For Africa',
    'Unity Bank',
    'UNIUYO Microfinance Bank Ltd',
    'Uzondu Microfinance Bank Awka Anambra State',
    'Vale Finance Limited',
    'Verification cannot be completed at the moment',
    'VFD Microfinance Bank Limited',
    'Victory MFB',
    'VISTA MFB',
    'Visual ICT Limited (TagPay)',
    'Waya Microfinance Bank',
    'Wema Bank',
    'Weston Charis MFB',
    'Whitecrust Finance Company',
    'Xpress Wallet',
    'YCT MFB',
    'Yes MFB',
    'Zap',
    'Zenith Bank',
    'Zitra MFB',
] as const
