# Generated by Django 5.1.6 on 2026-05-30 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_seed_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appuser',),
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appuser',),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appuser',),
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=120)),
                ('lga', models.CharField(max_length=120)),
                ('employment_status', models.CharField(max_length=40)),
                ('residence_country', models.CharField(max_length=100)),
                ('residence_state', models.CharField(max_length=120)),
                ('residence_city', models.CharField(max_length=120)),
                ('residence_lga', models.CharField(max_length=120)),
                ('residence_address', models.TextField()),
                ('length_of_stay', models.CharField(max_length=100)),
                ('housing_status', models.CharField(max_length=40)),
                ('employment_info', models.JSONField(blank=True, null=True)),
                ('financial_info', models.JSONField(blank=True, null=True)),
                ('guarantor_details', models.JSONField(blank=True, null=True)),
                ('landlord_info', models.JSONField(blank=True, null=True)),
                ('rental_history', models.JSONField(blank=True, null=True)),
                ('household_info', models.JSONField(blank=True, null=True)),
                ('social_presence', models.JSONField(blank=True, null=True)),
                ('criminal_declaration', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under review')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='tenant_profiles', to='core.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='core_tenantprof_status_ct_idx'), models.Index(fields=['user'], name='core_tenantprof_user_idx')],
            },
        ),
    ]
