# Generated by Django 5.1.6 on 2026-06-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_booking_rental_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandlordProfile",
            fields=[],
            options={
                "verbose_name": "Landlord Profile",
                "verbose_name_plural": "Landlord Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.appuser",),
        ),
    ]
