# Generated by Django 5.1.6 on 2026-06-20 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_landlordprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpayment',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredpayment',
            name='provider',
            field=models.CharField(default='flutterwave', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='flutterwave', max_length=40),
        ),
    ]
