# Generated by Django 6.1.1 on 2026-09-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_paymentsettlement_administration_fee_vat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Rental Payment', 'verbose_name_plural': 'Rental Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentsettlement',
            options={'verbose_name': 'Rentals Payments Settlement', 'verbose_name_plural': 'Rentals Payments Settlements'},
        ),
    ]
