# Generated by Django 6.1.1 on 2026-09-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='maximum_rental_duration',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
