# Generated by Django 6.1.1 on 2026-09-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_listing_location_and_fee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='boys_quarters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='caution_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnishing_level',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-furnished'), ('fully_furnished', 'Fully furnished')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='gated_estate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='legal_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='nearest_landmark',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pet_policy',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_supply',
            field=models.CharField(blank=True, choices=[('24_hours', '24-hour supply'), ('grid_with_backup', 'Grid + inverter/generator backup'), ('grid_only', 'Grid only'), ('limited', 'Limited supply')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='prepaid_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_tour_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='listing',
            name='water_supply',
            field=models.CharField(blank=True, choices=[('constant', 'Constant supply'), ('borehole', 'Borehole'), ('public_mains', 'Public mains'), ('tanker', 'Tanker delivery'), ('irregular', 'Irregular supply')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
