# Generated by Django 6.1.1 on 2026-09-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_listing_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettlement',
            name='purpose',
            field=models.CharField(choices=[('operations', 'RentDirect Administration Fee'), ('administration_fee_vat', 'VAT on RentDirect Administration Fee'), ('caution_fee', 'Refundable Caution Fee'), ('landlord_rent', 'Rent Amount')], max_length=30),
        ),
    ]
