# Generated by Django 6.1.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_paymentsettlement_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSearchRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_state', models.CharField(blank=True, default='', max_length=120)),
                ('preferred_city', models.CharField(blank=True, default='', max_length=120)),
                ('preferred_lga', models.CharField(blank=True, default='', max_length=120)),
                ('preferred_areas', models.CharField(blank=True, default='', max_length=255)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_nightly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, default='', max_length=80)),
                ('min_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_toilets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('furnishing_level', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-furnished'), ('fully_furnished', 'Fully furnished')], default='', max_length=20)),
                ('power_supply', models.CharField(blank=True, choices=[('24_hours', '24-hour supply'), ('grid_with_backup', 'Grid + inverter/generator backup'), ('grid_only', 'Grid only'), ('limited', 'Limited supply')], default='', max_length=20)),
                ('water_supply', models.CharField(blank=True, choices=[('constant', 'Constant supply'), ('borehole', 'Borehole'), ('public_mains', 'Public mains'), ('tanker', 'Tanker delivery'), ('irregular', 'Irregular supply')], default='', max_length=20)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('utilities_included', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('fitted_kitchen', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('boys_quarters', models.BooleanField(default=False)),
                ('prepaid_meter', models.BooleanField(default=False)),
                ('gated_estate', models.BooleanField(default=False)),
                ('security_guard', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('short_let_allowed', models.BooleanField(default=False)),
                ('student_tenants_allowed', models.BooleanField(default=False)),
                ('expatriates_allowed', models.BooleanField(default=False)),
                ('commercial_activities_allowed', models.BooleanField(default=False)),
                ('negotiable', models.BooleanField(default=False)),
                ('preferred_amenities', models.JSONField(blank=True, default=list)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('occupants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_requirement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
