# Generated by Django 6.1.1 on 2026-09-28 23:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_tenantsearchrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenancyAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('template_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('review', 'Review'), ('final', 'Final')], default='review', max_length=20)),
                ('agreement_data', models.JSONField(default=dict)),
                ('rendered_content', models.TextField()),
                ('document_hash', models.CharField(db_index=True, max_length=64)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_agreements', to='core.booking')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_tenancy_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['booking', '-generated_at'], name='core_tenancy_booking_gen_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'version'), name='core_tenancy_agreement_booking_version_uniq')],
            },
        ),
    ]
