# Generated by Django 6.1.1 on 2026-09-30 01:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_tenancyagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appuser',),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=160)),
                ('middle_name', models.CharField(blank=True, default='', max_length=160)),
                ('last_name', models.CharField(max_length=160)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=30)),
                ('nationality', models.CharField(default='Nigeria', max_length=80)),
                ('state_of_origin', models.CharField(blank=True, default='', max_length=120)),
                ('lga_of_origin', models.CharField(blank=True, default='', max_length=120)),
                ('mobile', models.CharField(blank=True, default='', max_length=40)),
                ('residential_address', models.TextField(blank=True, default='')),
                ('nin_number', models.CharField(blank=True, default='', max_length=80)),
                ('bvn_number', models.CharField(blank=True, default='', max_length=80)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_code', models.CharField(blank=True, default='', max_length=40)),
                ('account_name', models.CharField(blank=True, default='', max_length=160)),
                ('account_number', models.CharField(blank=True, default='', max_length=40)),
                ('verification_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('payment_required', 'Payment required'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='incomplete', max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['verification_status', '-updated_at'], name='core_agentprof_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('draft', 'Draft'), ('submitted', 'Submitted')], default='claimed', max_length=30)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('overall_status', models.CharField(blank=True, default='', max_length=40)),
                ('earning_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=30)),
                ('payout_reference', models.CharField(blank=True, default='', max_length=120)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('paid_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_inspections', to=settings.AUTH_USER_MODEL)),
                ('evidence_documents', models.ManyToManyField(blank=True, related_name='property_inspections', to='core.document')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='core.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'status', '-created_at'], name='core_insp_agent_status_idx'), models.Index(fields=['payout_status', '-submitted_at'], name='core_insp_payout_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('agent_verification', 'Agent Verification'), ('lawyer_tenancy', 'Lawyer Tenancy Agreement')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('provider', models.CharField(default='flutterwave', max_length=40)),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('provider_payload', models.JSONField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_payments', to='core.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='core_svcpay_user_purp_idx'), models.Index(fields=['booking', 'purpose', 'status'], name='core_svcpay_booking_idx')],
            },
        ),
    ]
