# Generated by Django 6.1.1 on 2026-09-30 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_agent_alter_appuser_role_alter_feedback_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_payments', to='core.listing'),
        ),
        migrations.AddField(
            model_name='tenancyagreement',
            name='docuseal_submission_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='purpose',
            field=models.CharField(choices=[('agent_verification', 'Agent Verification'), ('lawyer_tenancy', 'Lawyer Tenancy Agreement'), ('in_person_verification', 'In-Person Property Verification')], max_length=30),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('admin', 'Admin')], max_length=20)),
                ('password_hash', models.CharField(max_length=256)),
                ('otp_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='core_pendingreg_email_idx')],
            },
        ),
    ]
