# Generated by Django 6.1.1 on 2026-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_appuser_whatsapp_number_servicepayment_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='country_of_birth',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
