# Generated by Django 6.1.1 on 2026-09-30 23:01

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models

REFERRAL_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def backfill_referral_codes(apps, schema_editor):
    AgentProfile = apps.get_model("core", "AgentProfile")
    used = set(
        AgentProfile.objects.exclude(referral_code="").values_list("referral_code", flat=True)
    )
    for profile in AgentProfile.objects.filter(referral_code="").iterator():
        while True:
            code = "".join(secrets.choice(REFERRAL_CODE_ALPHABET) for _ in range(8))
            if code not in used:
                used.add(code)
                break
        profile.referral_code = code
        profile.save(update_fields=["referral_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_agentprofile_city_agentprofile_country_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Property Inspection Officer', 'verbose_name_plural': 'Property Inspection Officers'},
        ),
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'Property Inspection Officer Profile', 'verbose_name_plural': 'Property Inspection Officer Profiles'},
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Property Inspection Officer'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Property Inspection Officer'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Property Inspection Officer'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='purpose',
            field=models.CharField(choices=[('agent_verification', 'Property Inspection Officer Verification'), ('lawyer_tenancy', 'Lawyer Tenancy Agreement'), ('in_person_verification', 'In-Person Property Verification')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Property Inspection Officer'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='AgentReferralEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=30)),
                ('payout_reference', models.CharField(blank=True, default='', max_length=120)),
                ('paid_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_earning', to='core.propertyinspection')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_referral_earned', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIO Referral Earning',
                'verbose_name_plural': 'PIO Referral Earnings',
                'indexes': [models.Index(fields=['referrer', 'referred'], name='core_refearn_ref_idx'), models.Index(fields=['payout_status', '-created_at'], name='core_refearn_payout_idx')],
            },
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agentprofile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
    ]
