# Generated by Django 6.1.1 on 2026-10-01 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_agent_options_alter_agentprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_code', models.CharField(blank=True, default='', max_length=40)),
                ('account_number', models.CharField(max_length=40)),
                ('account_name', models.CharField(blank=True, default='', max_length=160)),
                ('transfer_recipient_id', models.CharField(blank=True, default='', max_length=120)),
                ('transfer_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('recipient_created', 'Recipient Created'), ('ready', 'Ready'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='scheduled', max_length=30)),
                ('provider_payload', models.JSONField(blank=True, null=True)),
                ('transfer_payload', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('process_at', models.DateTimeField()),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Refund',
                'verbose_name_plural': 'Tenant Refunds',
                'indexes': [models.Index(fields=['status', 'process_at'], name='core_refund_status_proc_idx'), models.Index(fields=['booking', '-created_at'], name='core_refund_booking_ct_idx')],
            },
        ),
    ]
