# Generated by Django 6.1.1 on 2026-10-01 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_tenantrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='authorization_letter',
            field=models.FileField(blank=True, upload_to='authorization_letters/'),
        ),
        migrations.CreateModel(
            name='RepresentativeKyc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ownership_type', models.CharField(blank=True, default='', max_length=120)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('nin_number', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_photo', models.FileField(blank=True, upload_to='representative_kyc/photos/')),
                ('id_document', models.FileField(blank=True, upload_to='representative_kyc/documents/')),
                ('return_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_payload', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_kycs', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_kycs', to='core.listing')),
            ],
            options={
                'verbose_name': 'Representative KYC',
                'verbose_name_plural': 'Representative KYCs',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='representative_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_listings', to='core.representativekyc'),
        ),
        migrations.AddIndex(
            model_name='representativekyc',
            index=models.Index(fields=['landlord', '-created_at'], name='core_repkyc_landlord_idx'),
        ),
        migrations.AddIndex(
            model_name='representativekyc',
            index=models.Index(fields=['status'], name='core_repkyc_status_idx'),
        ),
    ]
