# Generated by Django 6.1.1 on 2026-10-01 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_listing_authorization_letter_representativekyc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('taken', 'Request Accepted'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('notified_channels', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to='core.listing')),
            ],
            options={
                'verbose_name': 'Inspection Request',
                'verbose_name_plural': 'Inspection Requests',
                'indexes': [models.Index(fields=['agent', 'status', '-created_at'], name='core_inspreq_agent_idx'), models.Index(fields=['listing', 'status'], name='core_inspreq_listing_idx'), models.Index(fields=['status', 'expires_at'], name='core_inspreq_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'agent', 'round'), name='core_inspreq_unique_agent_round')],
            },
        ),
    ]
