# Generated by Django 6.1.1 on 2026-10-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_representativekyc_identity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='identity_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='physical_property_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='property_document_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
