# Generated by Devin on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_verificationrequest_identity_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='state_of_residence',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='city_of_residence',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
